### ISSUE TITLE
Deprecation Warning in yum

### ISSUE THREAD

**Issue by DirectorSloan** [idiv-biodiversity/ansible-role-nrpe#1]
[DEPRECATION WARNING]: Invoking "yum" only once while using a loop via squash_actions is deprecated. Instead of using a loop to supply multiple items and specifying `pkg: "{{ item }}"`, please use `pkg: 
['nrpe', 'nagios-plugins-load', 'nagios-plugins-procs', 'nagios-plugins-users', 'nagios-plugins-disk']` and remove the loop. This feature will be removed in version 2.11. Deprecation warnings can be 
disabled by setting deprecation_warnings=False in ansible.cfg.

**Comment by wookietreiber** [comment]
@sloan87 That's already the case, see [here](https://github.com/idiv-biodiversity/ansible-role-nrpe/blob/master/tasks/main.yml#L3). This has been fixed in **v1.0.2**, please make sure you use the latest version, which, as of now is **v1.0.4**.
